version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - '6379'
    networks:
      - backend

  db:
    image: mysql:5.7
    container_name: mysql-server
    ports:
      - '3306'
    environment:
      - MYSQL_USER: root
      - MYSQL_ROOT_PASSWORD: 546926936
      - MYSQL_PASSWORD: 546926936
      - MYSQL_DATABASE: dailyfresh
    command:
      --character-set-server=utf8mb4
      --explicit_defaults_for_timestamp=true
    volumes:
      - /mnt/dailyfresh/db_data:/var/lib/mysql:rw
    networks:
      - backend

  web:


